// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejwuhpxsegirgupezxem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqd3VocHhzZWdpcmd1cGV6eGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTUzODMsImV4cCI6MjA2MjMzMTM4M30.SlVT57z00fc6w6UDEyd6_r8_b3jHGzMNGYBfcKPiOMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);